"""empty message

Revision ID: 1dcece89832c
Revises: acb27a0bd893
Create Date: 2017-11-29 16:54:00.338034

"""

# revision identifiers, used by Alembic.
revision = '1dcece89832c'
down_revision = 'acb27a0bd893'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    # ### end Alembic commands ###
